title: Cameron Heinlein # your name (or website title) here
logo: "./images/cah.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Come take a look at some of the projects I have been working on through MIT Professional Certificate in Coding. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/cameronheinlein/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 
